# Github workflow to deploy to production in master branch 
name: deploy
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: copy file via ssh password
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.SSH_USER }}
        password: ${{ secrets.PASSWORD }}
        source: "test/"
        target: /var/www/${{secrets.SSH_USER}}/
    - name: deploy-ssh
      uses: garygrossgarten/github-action-ssh@release
      with:
        command: sh /deploy.sh
        host: ${{ secrets.HOST }}
        username: ${{ secrets.SSH_USER }}
        password: ${{ secrets.PASSWORD }}
