# Github workflow to deploy to production in master branch 
name: deploy
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CI: true
      LOCAL: test
    steps:
    - name: Copy folder content recursively to remote
      uses: garygrossgarten/github-action-scp@release 
      with:
        local: .
        remote: /var/www/${{secrets.SSH_USER}}/
        host: ${{ secrets.HOST }}
        username: ${{ secrets.SSH_USER }}
        password: ${{ secrets.PASSWORD }}
    - name: deploy-ssh
      uses: garygrossgarten/github-action-ssh@release
      with:
        command: sh /deploy.sh
        host: ${{ secrets.HOST }}
        username: ${{ secrets.SSH_USER }}
        password: ${{ secrets.PASSWORD }}
